version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/test
    overwrite: yes
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStart:
    - location: /opt/codedeploy-agent/deployment-root/9970eec0-9a21-470c-bdc4-d63c035dd893/d-CWNPUBC4I
      timeout: 60
      runas: ubuntu