version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/test
    overwrite: yes
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStart:
    - location: /
      timeout: 60
      runas: ubuntu