package com.jaks1m.project.common.exception;

import lombok.Getter;

@Getter
public enum ErrorCode {
    NOT_FOUND_USER (404,"NOT FOUND USER"),
    NOT_EQUAL_PASSWORD(404,"NOT EQUAL PASSWORD"),
    ALREADY_JOIN(404,"ALREADY JOIN"),
    ALREADY_WEB_JOIN(404,"ALREADY WEB JOIN"),
    LOGOUT_USER(401,"LOGOUT USER"),
    INCORRECT_PASSWORD(401,"INCORRECT PASSWORD"),
    ALREADY_FOLLOW(404,"ALREADY FOLLOW"),
    NOT_FOUND_FOLLOW(404,"NOT FOUND FOLLOW"),
    NOT_FOUND_COMMENT(404,"NOT FOUND COMMENT"),
    NOT_CONVERT_FILE(404,"NOT CONVERT FILE"),
    IMAGE_NOT_FOUND(404,"IMAGE NOT FOUND"),
    JWT_ACCESS_TOKEN_EXPIRED(401,"ACCESS TOKEN EXPIRED"),
    JWT_REFRESH_TOKEN_EXPIRED(401,"REFRESH TOKEN EXPIRED"),
    JWT_UNAUTHORIZED(401,"UNAUTHORIZED TOKEN"),
    JWT_INVALID_SIGNATURE(401,"INVALID SIGNATURE"),
    JWT_UNSUPPORTED(401,"UNSUPPORTED TOKEN"),
    JWT_CLAIMS_EMPTY(401,"CLAIMS_EMPTY"),
    JWT_BLACKLIST(401,"TOKEN IS BLACKLIST"),
    EMAIL_TOKEN_NOT_FOUND(404,"EMAIL TOKEN NOT FOUND"),
    NOT_FOUND_AUTHENTICATION(401,"NOT FOUND AUTHENTICATION"),
    ACCESS_DENIED(403,"ACCESS_DENIED"),
    NOT_FOUND_BOARD(404,"NOT FOUND BOARD"),
    NOT_FOUND_TODO(404,"NOT FOUND TODO"),
    NOT_FOUND_SCHEDULE(404,"NOT FOUND SCHEDULE"),
    NOT_FOUND_HEART(404,"NOT FOUND HEART"),
    NOT_FOUND_NOTIFICATION(404,"NOT FOUND NOTIFICATION"),
    UNAUTHORIZED_USER(401,"UNAUTHORIZED USER");

    ErrorCode(int status,String message) {
        this.status=status;
        this.message=message;
    }
    private int status;
    private String message;
}
