spring:
  profiles:
    include: oauth
  datasource:
    url:
    username: opqrs1107
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
  redis:
    host:
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: opqrs1103@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 3000
          timeout: 3000
          write timeout: 3000
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    s3:
      bucket: jaksim-image
    region:
      static: ap-northeast-2
    stack:
      auto: false

jwt:
  secret:
  response:
    header:
      Authorization
  token:
    prefix:
      Bearer

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace


