spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 431e8670b8618bd10b694d1ec5e1fb6c
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            #http://jaks1m.shop:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            client-secret: jkYAUF99oipotGKpH27QatwZHaOqHTeB
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
            client_name: kakao
          naver:
            client-id: HqJRICqZye6EyZWC2O5s
            client-secret: RN2bkL4Kmq
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            #http://jaks1m.shop:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          google:
            client-id: 776510106596-ds3v5gj0n9l9f4b03680tn8orkbrogkd.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
