spring:
  profiles:
    include: oauth
  datasource:
    url: jdbc:mariadb://localhost:3306/dev?autoReconnect=true
    #jdbc:mariadb://jaksim.cuazjhwugow7.ap-northeast-2.rds.amazonaws.com:3306/dev?autoReconnect=true
    username: root
    #opqrs1107
    password: Janghojin00@
    #janghojin00
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
  redis:
    host: localhost
    #jaksim-001.tcmnx1.0001.apn2.cache.amazonaws.com
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: opqrs1103@gmail.com
    password: uapdfwcwqnfdsmqe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 3000
          timeout: 3000
          write timeout: 3000
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
jwt:
  security:
    key:
      my-secret-key
  response:
    header:
      Authorization
  token:
    prefix:
      Bearer


