spring:
  profiles:
    include: oauth
  datasource:
    url: jdbc:mariadb://localhost:3306/dev?autoReconnect=true
#jdbc:mariadb://ec2-15-165-196-158.ap-northeast-2.compute.amazonaws.com/dev?autoReconnect=true
    username: root
    password: Janghojin00@
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
  redis:
    host: localhost
    port: 6379
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
jwt:
  security:
    key:
      my-secret-key
  response:
    header:
      Authorization
  token:
    prefix:
      Bearer


