package com.jaks1m.project.domain.error;

import lombok.Getter;

@Getter
public enum ErrorCode {
    NOT_FOUND_USER (404,"U001","NOT FOUND USER"),
    NOT_EQUAL_PASSWORD(404,"U002","NOT EQUAL PASSWORD"),
    ALREADY_JOIN(404,"U003","ALREADY JOIN"),
    ALREADY_WEB_JOIN(404,"U004","ALREADY WEB JOIN"),
    LOGOUT_USER(404,"U003","LOGOUT USER"),
    INCORRECT_PASSWORD(400,"U005","INCORRECT PASSWORD"),
    NOT_CONVERT_FILE(404,"U006","NOT CONVERT FILE"),
    IMAGE_NOT_FOUND(404,"U007","IMAGE NOT FOUND"),
    JWT_ACCESS_TOKEN_EXPIRED(401,"T001","ACCESS TOKEN EXPIRED"),
    JWT_REFRESH_TOKEN_EXPIRED(401,"T002","REFRESH TOKEN EXPIRED"),
    JWT_UNAUTHORIZED(401,"T003","UNAUTHORIZED TOKEN"),
    JWT_INVALID_SIGNATURE(401,"T004","INVALID SIGNATURE"),
    JWT_UNSUPPORTED(401,"T005","UNSUPPORTED TOKEN"),
    JWT_CLAIMS_EMPTY(401,"T006","CLAIMS_EMPTY"),
    JWT_BLACKLIST(401,"T007","TOKEN IS BLACKLIST"),
    EMAIL_TOKEN_NOT_FOUND(401,"T008","EMAIL TOKEN NOT FOUND"),
    NOT_FOUND_AUTHENTICATION(401,"S001","NOT FOUND AUTHENTICATION"),
    NOT_FOUND_BOARD(404,"B001","NOT FOUND BOARD"),
    NOT_FOUND_TODO(404,"M001","NOT FOUND TODO"),
    NOT_FOUND_SCHEDULE(404,"S001","NOT FOUND SCHEDULE"),

    UNAUTHORIZED_USER(404,"U008","UNAUTHORIZED USER");


    ErrorCode(int status,String code,String message) {
        this.status=status;
        this.code=code;
        this.message=message;
    }

    private int status;
    private String code;
    private String message;
}
