name: jaksim

on:
  push: # 적용될 액션
    branches: main # 적용될 브랜치

jobs:
  deploy:
    runs-on: ubuntu-latest # 인스턴스 OS
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2 # 워크플로에서 액세스할 수 있도록 에서 저장소를 체크아웃

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: S3 Deploy
        run: aws s3 sync ./dist s3://jaksim/ --acl bucket-owner-full-control # s3 이름 2021-cvi-dev
        env:
          AWS_ACCESS_KEY_ID: AKIAVA3E5BCWPN2UJC5T
          AWS_SECRET_ACCESS_KEY: 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
          AWS_REGION: ap-northeast-2
